strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
  - checkout: self
    submodules: true
  - task: VSBuild@1
    inputs:
      solution: msdf-atlas-gen.sln
      vsVersion: '16.0'
      msbuildArgs: /p:PlatformToolset=v142
      platform: 'x64'
      configuration: 'release'
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - bash: |
      make
      ls bin
    condition: ne( variables['Agent.OS'], 'Windows_NT' )