strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
  - task: VSBuild@1
    inputs:
      solution: msdf-atlas-gen.sln
      vsVersion: '15.0'
      platform: 'x64'
      configuration: 'release'
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - bash: make
    condition: ne( variables['Agent.OS'], 'Windows_NT' )