strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
  - checkout: self
    submodules: true
  - bash: msbuild msdf-atlas-gen /p:PlatformToolset=v142 /p:Platform="x64" /p:Configuration="Release"
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - bash: make
    condition: ne( variables['Agent.OS'], 'Windows_NT' )