name: Unix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: make
      run: make
    - name: zip
      run: tar -czvf ${{ matrix.os }}.tar.gz -C bin msdf-atlas-gen
    - name: Upload Artefacts
      uses: AButler/upload-release-assets@v2.0
      with:
        files: '${{ matrix.os }}.tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: CI
