name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: make
      run: msbuild /p:Platform=x64 /p:Configuration=Release /p:PlatformToolset=v142 /p:WindowsTargetPlatformVersion=10.0
    - name: zip
      run: tar -a -c -f windows-latest.zip -C x64/Release msdf-atlas-gen.exe
    - name: Upload Artefacts
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'windows-latest.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: CI
